--Some analysis (exploratory data analysis)
-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

--Explore all countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers

--Explore all categories our customers come from
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
ORDER BY 1,2,3

--Find date of first and last order
--Find duration of sales
SELECT 
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date ,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS duration_in_years
FROM gold.fact_sales

--Find youngest and oldest customer
SELECT
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year,MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers

--Find the Total Sales
SELECT SUM(sales_amount) AS Total_sales FROM gold.fact_sales

--Find how many items are sold
SELECT SUM(quantity) AS quatity_sold FROM gold.fact_sales

--Find the average selling price
SELECT avg(price) AS avg_price FROM gold.fact_sales

--Find the Total number of orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders_distinct FROM gold.fact_sales

--Find the Total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) AS total_products_distinct FROM gold.dim_products

--Find the Total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers

--Find the Total number of customers that has places an order

SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales

--Generate a report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name, sum(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, sum(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' as measure_name, avg(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Of Orders' as measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Of Products' as measure_name,  COUNT(product_name) AS measure_value  FROM gold.dim_products
UNION ALL
SELECT 'Total No. Of Customers' as measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total No. Of Customers who ordered' as measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales


-- Find total customers by countries
SELECT 
country,
Count(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
-- Find total customers by gender
SELECT 
gender,
Count(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC
-- Find total customers by category
SELECT 
category,
Count(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC
-- What is the total average costs in each category
SELECT 
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key= f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find the total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key= f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name 
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key= f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC

--Which 5 products generate the highest revenue? 
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key= f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

SELECT* 
FROM (
SELECT 
p.product_name,
SUM(f.sales_amount) AS total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) as rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key= f.product_key
GROUP BY p.product_name)t
WHERE rank_products <=5


--Which 5 products generate the lowest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key= f.product_key
GROUP BY p.product_name
ORDER BY total_revenue 

--Find top 10 customers who have generated the highest revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key= f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name 
ORDER BY total_revenue DESC

--Find the 3 customers with the fewest orders placed
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS no_of_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key= f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name 
ORDER BY no_of_orders 
